/*
 *
 * implementer constants
 *
 */
export const FETCH_IMPLEMENTERS = 'src/Implementer/FETCH_IMPLEMENTERS';
export const FETCH_IMPLEMENTERS_SELECT='src/Implementer/FETCH_IMPLEMENTERS_SELECT';
export const REMOVE_IMPLEMENTERS = 'src/Implementer/REMOVE_IMPLEMENTERS';
export const IMPLEMENTER_FORM_CHANGE = 'src/Implementer/IMPLEMENTER_FORM_CHANGE';
export const SET_IMPLEMENTER_FORM_ERRORS = 'src/Implementer/SET_IMPLEMENTER_FORM_ERRORS';
export const IMPLEMENTER_FORM_RESET = 'src/Implementer/IMPLEMENTER_FORM_RESET';
export const SIGNUP_CHANGE = 'src/Implementer/SIGNUP_CHANGE';
export const SET_SIGNUP_FORM_ERRORS = 'src/Implementer/SET_SIGNUP_FORM_ERRORS';
export const SET_IMPLEMENTERS_LOADING = 'src/Implementer/SET_IMPLEMENTERS_LOADING';
export const SET_IMPLEMENTER_SUBMITTING = 'src/Implementer/SET_IMPLEMENTER_SUBMITTING';
export const SET_IMPLEMENTER_LOADING = 'src/Implementer/SET_IMPLEMENTER_LOADING';
export const SIGNUP_RESET = 'src/Implementer/SIGNUP_RESET';
export const SET_ASSIGNED_IMPLEMENTERS_LOADING = 'src/Implementer/SET_ASSIGNED_IMPLEMENTERS_LOADING';
export const FETCH_IMPLEMENTERS_FRAMEWORKS = 'src/Implementer/FETCH_IMPLEMENTERS_FRAMEWORKS';